# Influnece of method


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Daten Einlesen


In [12]:
dfref500rpm = pd.read_excel('data/Dicke500rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])
dfref750rpm = pd.read_excel('data/Dicke750rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])
dfref1000rpm = pd.read_excel('data/Dicke1000rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])
dfref2000rpm = pd.read_excel('data/Dicke2000rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])
dfref3000rpm = pd.read_excel('data/Dicke3000rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])
dfref4000rpm = pd.read_excel('data/Dicke4000rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])
dfref5000rpm = pd.read_excel('data/Dicke5000rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])
dfref6000rpm = pd.read_excel('data/Dicke6000rpm_refl.xls',header = None, names = ['Nr.', 'd', 'xfit'])


## Funktionen


In [25]:
def mittelwert(df):
    return np.array([np.mean(df.loc[:,'d']), np.std(df.loc[:,'d']), np.mean(df.loc[:,'d'])/ np.std(df.loc[:,'d'])])



In [30]:
heterogeneity_ref = mittelwert(dfref500rpm)
for i in [dfref750rpm ,dfref1000rpm,dfref2000rpm,dfref3000rpm,dfref4000rpm,dfref5000rpm,dfref6000rpm]:
    heterogeneity_ref = np.vstack((heterogeneity_ref, mittelwert(i)))


[[894.55        28.87979397  30.97494396]
 [740.48333333   8.17382339  90.59203968]
 [604.6          5.35568234 112.88944369]
 [466.71666667   6.81356898  68.49812017]
 [405.21666667   7.19036779  56.35548539]
 [360.85         7.48325909  48.22096836]
 [329.66666667  14.92633765  22.0862394 ]
 [302.68333333   5.32366311  56.85621483]]
